name: Python application

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            appname: app
          - os: windows-2019
            appname: app.exe
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "construct==2.10.70" "pyinstaller==6.11.1"
      - name: Build executable
        run: |
          pyinstaller -F app.py
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: hlsb_app_${{ matrix.os }}
          path: dist/${{ matrix.appname }}
